
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label lcalculadora;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Entry pantalla;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Button botonvaciar;

	private global::Gtk.Button botonborra;

	private global::Gtk.HBox hbox11;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button boton7;

	private global::Gtk.Button boton8;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Button boton9;

	private global::Gtk.Button botondiv;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox8;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button boton4;

	private global::Gtk.Button boton5;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button boton6;

	private global::Gtk.Button botonmult;

	private global::Gtk.HBox hbox5;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button boton1;

	private global::Gtk.Button boton2;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button boton3;

	private global::Gtk.Button botonmenos;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button boton;

	private global::Gtk.Button botoncoma;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button botonigual;

	private global::Gtk.Button botonsuma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lcalculadora = new global::Gtk.Label();
		this.lcalculadora.HeightRequest = 30;
		this.lcalculadora.Name = "lcalculadora";
		this.lcalculadora.LabelProp = global::Mono.Unix.Catalog.GetString("Mi Calculadora");
		this.vbox1.Add(this.lcalculadora);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lcalculadora]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.pantalla = new global::Gtk.Entry();
		this.pantalla.HeightRequest = 50;
		this.pantalla.CanFocus = true;
		this.pantalla.Name = "pantalla";
		this.pantalla.IsEditable = false;
		this.pantalla.InvisibleChar = '•';
		this.vbox2.Add(this.pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.pantalla]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.botonvaciar = new global::Gtk.Button();
		this.botonvaciar.WidthRequest = 300;
		this.botonvaciar.HeightRequest = 50;
		this.botonvaciar.CanFocus = true;
		this.botonvaciar.Name = "botonvaciar";
		this.botonvaciar.UseUnderline = true;
		this.botonvaciar.Label = global::Mono.Unix.Catalog.GetString("A/C");
		this.hbox14.Add(this.botonvaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.botonvaciar]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.botonborra = new global::Gtk.Button();
		this.botonborra.WidthRequest = 105;
		this.botonborra.HeightRequest = 50;
		this.botonborra.CanFocus = true;
		this.botonborra.Name = "botonborra";
		this.botonborra.UseUnderline = true;
		this.botonborra.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox14.Add(this.botonborra);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.botonborra]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add(this.hbox14);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox14]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.boton7 = new global::Gtk.Button();
		this.boton7.WidthRequest = 100;
		this.boton7.HeightRequest = 50;
		this.boton7.CanFocus = true;
		this.boton7.Name = "boton7";
		this.boton7.UseUnderline = true;
		this.boton7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox13.Add(this.boton7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.boton7]));
		w6.Position = 0;
		// Container child hbox13.Gtk.Box+BoxChild
		this.boton8 = new global::Gtk.Button();
		this.boton8.WidthRequest = 101;
		this.boton8.HeightRequest = 50;
		this.boton8.CanFocus = true;
		this.boton8.Name = "boton8";
		this.boton8.UseUnderline = true;
		this.boton8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox13.Add(this.boton8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.boton8]));
		w7.Position = 1;
		this.hbox11.Add(this.hbox13);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox13]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.boton9 = new global::Gtk.Button();
		this.boton9.WidthRequest = 100;
		this.boton9.HeightRequest = 50;
		this.boton9.CanFocus = true;
		this.boton9.Name = "boton9";
		this.boton9.UseUnderline = true;
		this.boton9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox12.Add(this.boton9);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.boton9]));
		w9.Position = 0;
		// Container child hbox12.Gtk.Box+BoxChild
		this.botondiv = new global::Gtk.Button();
		this.botondiv.WidthRequest = 90;
		this.botondiv.HeightRequest = 50;
		this.botondiv.CanFocus = true;
		this.botondiv.Name = "botondiv";
		this.botondiv.UseUnderline = true;
		this.botondiv.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox12.Add(this.botondiv);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.botondiv]));
		w10.Position = 1;
		this.hbox11.Add(this.hbox12);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox12]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox2.Add(this.hbox11);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox11]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.boton4 = new global::Gtk.Button();
		this.boton4.WidthRequest = 100;
		this.boton4.HeightRequest = 50;
		this.boton4.CanFocus = true;
		this.boton4.Name = "boton4";
		this.boton4.UseUnderline = true;
		this.boton4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox10.Add(this.boton4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.boton4]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.boton5 = new global::Gtk.Button();
		this.boton5.WidthRequest = 100;
		this.boton5.HeightRequest = 50;
		this.boton5.CanFocus = true;
		this.boton5.Name = "boton5";
		this.boton5.UseUnderline = true;
		this.boton5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox10.Add(this.boton5);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.boton5]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox8.Add(this.hbox10);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox10]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.boton6 = new global::Gtk.Button();
		this.boton6.WidthRequest = 100;
		this.boton6.HeightRequest = 50;
		this.boton6.CanFocus = true;
		this.boton6.Name = "boton6";
		this.boton6.UseUnderline = true;
		this.boton6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox9.Add(this.boton6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.boton6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.botonmult = new global::Gtk.Button();
		this.botonmult.WidthRequest = 90;
		this.botonmult.HeightRequest = 50;
		this.botonmult.CanFocus = true;
		this.botonmult.Name = "botonmult";
		this.botonmult.UseUnderline = true;
		this.botonmult.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox9.Add(this.botonmult);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.botonmult]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox8.Add(this.hbox9);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox9]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox3.Add(this.hbox8);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.boton1 = new global::Gtk.Button();
		this.boton1.WidthRequest = 100;
		this.boton1.HeightRequest = 50;
		this.boton1.CanFocus = true;
		this.boton1.Name = "boton1";
		this.boton1.UseUnderline = true;
		this.boton1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox7.Add(this.boton1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.boton1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.boton2 = new global::Gtk.Button();
		this.boton2.WidthRequest = 100;
		this.boton2.HeightRequest = 50;
		this.boton2.CanFocus = true;
		this.boton2.Name = "boton2";
		this.boton2.UseUnderline = true;
		this.boton2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox7.Add(this.boton2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.boton2]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox5.Add(this.hbox7);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox7]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.boton3 = new global::Gtk.Button();
		this.boton3.WidthRequest = 100;
		this.boton3.HeightRequest = 50;
		this.boton3.CanFocus = true;
		this.boton3.Name = "boton3";
		this.boton3.UseUnderline = true;
		this.boton3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox6.Add(this.boton3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.boton3]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.botonmenos = new global::Gtk.Button();
		this.botonmenos.WidthRequest = 90;
		this.botonmenos.HeightRequest = 50;
		this.botonmenos.CanFocus = true;
		this.botonmenos.Name = "botonmenos";
		this.botonmenos.UseUnderline = true;
		this.botonmenos.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox6.Add(this.botonmenos);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.botonmenos]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.hbox5.Add(this.hbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.boton = new global::Gtk.Button();
		this.boton.WidthRequest = 100;
		this.boton.HeightRequest = 50;
		this.boton.CanFocus = true;
		this.boton.Name = "boton";
		this.boton.UseUnderline = true;
		this.boton.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox2.Add(this.boton);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.boton]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.botoncoma = new global::Gtk.Button();
		this.botoncoma.WidthRequest = 100;
		this.botoncoma.HeightRequest = 50;
		this.botoncoma.CanFocus = true;
		this.botoncoma.Name = "botoncoma";
		this.botoncoma.UseUnderline = true;
		this.botoncoma.Label = global::Mono.Unix.Catalog.GetString(",");
		this.hbox2.Add(this.botoncoma);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.botoncoma]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.botonigual = new global::Gtk.Button();
		this.botonigual.WidthRequest = 100;
		this.botonigual.HeightRequest = 50;
		this.botonigual.CanFocus = true;
		this.botonigual.Name = "botonigual";
		this.botonigual.UseUnderline = true;
		this.botonigual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox4.Add(this.botonigual);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.botonigual]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.botonsuma = new global::Gtk.Button();
		this.botonsuma.WidthRequest = 90;
		this.botonsuma.HeightRequest = 50;
		this.botonsuma.CanFocus = true;
		this.botonsuma.Name = "botonsuma";
		this.botonsuma.UseUnderline = true;
		this.botonsuma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox4.Add(this.botonsuma);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.botonsuma]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		this.hbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox4]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w34.Position = 2;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 418;
		this.DefaultHeight = 366;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.botonvaciar.Clicked += new global::System.EventHandler(this.OnBotonvaciarClicked);
		this.botonborra.Clicked += new global::System.EventHandler(this.OnBotonborraClicked);
		this.boton7.Clicked += new global::System.EventHandler(this.OnBoton7Clicked);
		this.boton8.Clicked += new global::System.EventHandler(this.OnBoton8Clicked);
		this.boton9.Clicked += new global::System.EventHandler(this.OnBoton9Clicked);
		this.botondiv.Clicked += new global::System.EventHandler(this.OnBotondivClicked);
		this.boton4.Clicked += new global::System.EventHandler(this.OnBoton4Clicked);
		this.boton5.Clicked += new global::System.EventHandler(this.OnBoton5Clicked);
		this.boton6.Clicked += new global::System.EventHandler(this.OnBoton6Clicked);
		this.botonmult.Clicked += new global::System.EventHandler(this.OnBotonmultClicked);
		this.boton1.Clicked += new global::System.EventHandler(this.OnBoton1Clicked);
		this.boton2.Clicked += new global::System.EventHandler(this.OnBoton2Clicked);
		this.boton3.Clicked += new global::System.EventHandler(this.OnBoton3Clicked);
		this.botonmenos.Clicked += new global::System.EventHandler(this.OnBotonmenosClicked);
		this.boton.Clicked += new global::System.EventHandler(this.OnBotonClicked);
		this.botoncoma.Clicked += new global::System.EventHandler(this.OnBotoncomaClicked);
		this.botonigual.Clicked += new global::System.EventHandler(this.OnBotonigualClicked);
		this.botonsuma.Clicked += new global::System.EventHandler(this.OnBotonsumaClicked);
	}
}
